const $=x=>document.getElementById(x),c=$("c"),ctx=c.getContext("2d");
let pos=null,route=null,coords=[],idx=0,heading=null,watch=null,mode="route",lastRecalc=0;
const ROUTER="https://router.project-osrm.org/route/v1/driving",GEOCODER="https://nominatim.openstreetmap.org/search";
function resize(){let d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+"px";c.style.height=innerHeight+"px";ctx.setTransform(d,0,0,d,0,0);draw()}addEventListener("resize",resize);resize();
const rad=x=>x*Math.PI/180;
function hav(a,b){let R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function bear(a,b){let p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lon-a.lon);return (Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360}
function diff(a,b){return((b-a+540)%360)-180}
function fd(m){return m<1000?Math.max(1,Math.round(m/10)*10)+" m":(m/1000).toFixed(1)+" km"}
async function geo(q){let r=await fetch(GEOCODER+"?format=jsonv2&limit=1&countrycodes=ar&q="+encodeURIComponent(q),{headers:{Accept:"application/json"}}),d=await r.json();if(!d.length)throw Error("No encontré ese destino");return{lat:+d[0].lat,lon:+d[0].lon}}
async function getRoute(a,b){let u=`${ROUTER}/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=true`,r=await fetch(u),d=await r.json();if(d.code!=="Ok")throw Error("No se pudo calcular la ruta");return d.routes[0]}
function nearest(){let best=idx,bd=1e99;for(let i=Math.max(0,idx-5);i<Math.min(coords.length,idx+160);i++){let d=hav(pos,{lat:coords[i][1],lon:coords[i][0]});if(d<bd){bd=d;best=i}}return{idx:best,d:bd}}
function remain(i){let d=0;for(let j=i;j<coords.length-1;j++)d+=hav({lat:coords[j][1],lon:coords[j][0]},{lat:coords[j+1][1],lon:coords[j+1][0]});return d}
function nextTurn(i){for(let k=i+8;k<coords.length-8;k+=2){let a=bear({lat:coords[k-8][1],lon:coords[k-8][0]},{lat:coords[k][1],lon:coords[k][0]}),b=bear({lat:coords[k][1],lon:coords[k][0]},{lat:coords[k+8][1],lon:coords[k+8][0]}),dd=diff(a,b);if(Math.abs(dd)>28){let d=0;for(let j=i;j<k;j++)d+=hav({lat:coords[j][1],lon:coords[j][0]},{lat:coords[j+1][1],lon:coords[j+1][0]});return{d,icon:dd>0?"↱":"↰",text:dd>0?"Doblá a la derecha":"Doblá a la izquierda",at:k}}}return{d:remain(i),icon:"↑",text:"Seguí derecho",at:coords.length-1}}
function project(p){let sc=Math.min(innerWidth,innerHeight)/.012,lat0=rad(pos.lat);return[(p[0]-pos.lon)*Math.cos(lat0)*sc+innerWidth/2,(pos.lat-p[1])*sc+innerHeight*.43]}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);if(!pos)return;
 if(mode==="compass"){let target=bear(pos,route.dest),rel=diff(heading??target,target),cx=innerWidth/2,cy=innerHeight*.43;ctx.save();ctx.translate(cx,cy);ctx.rotate(rad(rel));ctx.strokeStyle="#f2f2f2";ctx.lineWidth=8;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(0,140);ctx.lineTo(0,-90);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(0,-120);ctx.lineTo(23,-75);ctx.lineTo(0,-88);ctx.lineTo(-23,-75);ctx.closePath();ctx.fill();ctx.restore();$("mi").textContent="◎";$("dist").textContent=fd(hav(pos,route.dest));$("inst").textContent="Hacia el destino";$("remain").textContent=fd(hav(pos,route.dest));return}
 if(!coords.length)return;let end=Math.min(coords.length-1,idx+180);ctx.strokeStyle="#f2f2f2";ctx.lineWidth=7;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();for(let i=Math.max(0,idx-3);i<=end;i++){let [x,y]=project(coords[i]);i===Math.max(0,idx-3)?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();
 let [x,y]=project([pos.lon,pos.lat]),h=heading??bear(pos,{lat:coords[Math.min(idx+4,coords.length-1)][1],lon:coords[Math.min(idx+4,coords.length-1)][0]});ctx.save();ctx.translate(x,y);ctx.rotate(-rad(h));ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(17,18);ctx.lineTo(0,10);ctx.lineTo(-17,18);ctx.closePath();ctx.fill();ctx.restore()}
function update(){if(!pos)return;if(mode==="compass"){draw();return}let n=nearest();idx=n.idx;let m=nextTurn(idx);$("dist").textContent=fd(m.d);$("mi").textContent=m.icon;$("inst").textContent=m.text;$("remain").textContent=fd(remain(idx));$("speed").textContent=Math.round(Math.max(0,(pos.speed||0)*3.6));$("dot").classList.add("ok");$("gps").textContent="GPS";draw();if(n.d>80&&Date.now()-lastRecalc>15000)recalc()}
async function recalc(){if(!pos||!route?.dest)return;lastRecalc=Date.now();$("recalc").classList.remove("hidden");try{route=await getRoute(pos,route.dest);coords=route.geometry.coordinates;idx=0;$("recalc").classList.add("hidden");update()}catch(e){setTimeout(()=>$("recalc").classList.add("hidden"),1500)}}
async function start(q,compass=false){$("status").textContent="Buscando destino…";try{let dest=await geo(q);if(!pos)await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>{pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed};ok()},no,{enableHighAccuracy:true,timeout:15000,maximumAge:5000}));mode=compass?"compass":"route";route={dest};if(!compass){route=await getRoute(pos,dest);route.dest=dest;coords=route.geometry.coordinates;idx=0}$("home").classList.add("hidden");$("nav").classList.remove("hidden");startSensors();startGPS();update()}catch(e){$("status").textContent=e.message||"Error"}}
function startGPS(){if(watch!=null)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(p=>{pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed};update()},()=>{$("gps").textContent="GPS sin señal";$("dot").classList.remove("ok")},{enableHighAccuracy:true,maximumAge:1000,timeout:10000})}
function startSensors(){if("wakeLock"in navigator)navigator.wakeLock.request("screen").catch(()=>{});let f=e=>{let h=typeof e.webkitCompassHeading==="number"?e.webkitCompassHeading:(typeof e.alpha==="number"?(360-e.alpha)%360:null);if(h!=null)heading=h;draw()};addEventListener("deviceorientationabsolute",f,true);addEventListener("deviceorientation",f,true)}
$("start").onclick=()=>start($("dest").value.trim());$("compass").onclick=()=>start($("dest").value.trim(),true);$("dest").onkeydown=e=>{if(e.key==="Enter")$("start").click()};$("exit").onclick=()=>{if(watch!=null)navigator.geolocation.clearWatch(watch);$("nav").classList.add("hidden");$("home").classList.remove("hidden");route=null;coords=[];pos=null;heading=null};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
